version: '3.8'

networks:
  traefik:
    external: true
  bridge:

volumes:
  pg-data:
    external: true
  rabbitmq-data:
    external: true

services:
  app:
    image: ghcr.io/psychofanimal/credit-car/php:latest
    platform: linux/amd64
    depends_on:
      - db
    networks:
      - bridge
      - traefik
    volumes:
      - ./api:/app

  http:
    image: nginx:latest
    command: [ "nginx", "-g", "daemon off;" ]
    depends_on:
      - app
    labels:
      - traefik.enable=true
      - traefik.http.routers.http.rule=Host(`api.docker.ru`)
      - traefik.http.routers.http.entrypoints=web, websecure
      - traefik.http.routers.http.tls=true
      - traefik.docker.network=traefik
      - traefik.http.services.http.loadBalancer.server.port=80
    networks:
      - bridge
      - traefik
    volumes:
      - ./api:/app
      - .docker/nginx/common.conf:/etc/nginx/common.conf:ro
      - .docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf:ro

  db:
    image: ghcr.io/psychofanimal/credit-car/database:latest
    networks:
      - bridge
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data:rw
